let docs = [], active = null;
const $ = id => document.getElementById(id), api = (u, o) => fetch(u, o).then(r => r.json());
function status(s) { $('state').textContent = s }
$('file').onchange = e => e.target.files[0] && upload(e.target.files[0]);
$('drop').ondragover = e => { e.preventDefault(); $('drop').style.borderColor = 'var(--acid)' };
$('drop').ondrop = e => { e.preventDefault(); $('drop').style.borderColor = ''; e.dataTransfer.files[0] && upload(e.dataTransfer.files[0]) };
async function upload(file) { if (!file.name.toLowerCase().endsWith('.pdf')) return alert('PDF only'); status('PROCESSING'); let fd = new FormData(); fd.append('file', file); let d = await api('/api/upload', { method: 'POST', body: fd }); docs.push(d); active = d.id; showApp(); renderDocs(); renderActive(); status('INDEXED') }
function showApp() { $('landing').classList.add('hidden'); $('app').classList.remove('hidden') }
function renderDocs() { $('docs').innerHTML = docs.map(d => `<div class="docItem ${d.id === active ? 'active' : ''}" onclick="selectDoc('${d.id}')">${esc(d.name)}</div>`).join(''); buildPick() }
function selectDoc(id) { active = id; renderDocs(); renderActive(); $('messages').innerHTML = '<div class="empty"><strong>Document indexed.</strong><span>Ask a factual question about its contents.</span></div>' }
function renderActive() { let d = docs.find(x => x.id === active); if (!d) return; $('title').textContent = d.name; $('meta').textContent = 'PDF DOCUMENT'; $('words').textContent = d.stats.words + ' words'; $('pages').textContent = d.pages + ' pages'; $('chunks').textContent = d.chunks + ' chunks' }
$('new').onclick = () => { $('file').click() };
$('ask').onsubmit = async e => { e.preventDefault(); let q = $('q').value.trim(); if (!q) return; $('q').value = ''; add('YOU', q, 'user'); add('DOCLENS', 'Retrieving relevant passages…', 'bot', 'loading'); let d = await api('/api/ask', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ document_id: active, question: q }) }); document.querySelector('.loading')?.remove(); add('DOCLENS', d.answer, 'bot', null, d.sources) };
function add(role, text, type, cl = '', sources = []) { let x = document.createElement('div'); x.className = 'msg ' + type + ' ' + cl; x.innerHTML = `<div class="role">${role}</div><div class="bubble"></div>`; x.querySelector('.bubble').textContent = text; if (sources.length) { let s = document.createElement('div'); s.className = 'sources'; sources.forEach(a => { let b = document.createElement('span'); b.className = 'source'; b.textContent = `PAGE ${a.page} · ${a.score}`; s.appendChild(b) }); x.appendChild(s) } $('messages').appendChild(x); $('messages').scrollTop = $('messages').scrollHeight }
$('sum').onclick = async () => { let d = await api('/api/summarize', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ document_id: active }) }); $('sumText').textContent = d.summary };
function buildPick() { $('pick').innerHTML = docs.map(d => `<label class="check"><input type="checkbox" value="${d.id}"> ${esc(d.name)}</label>`).join('') }
$('cmp').onclick = async () => { let ids = [...document.querySelectorAll('#pick input:checked')].map(x => x.value), q = $('cq').value.trim() || 'Compare the key information and important differences.'; if (ids.length < 2) return alert('Select at least two PDFs'); $('cmpText').textContent = 'Comparing…'; let d = await api('/api/compare', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ document_ids: ids, question: q }) }); $('cmpText').textContent = d.answer };
document.querySelectorAll('.tab').forEach(b => b.onclick = () => { document.querySelectorAll('.tab').forEach(x => x.classList.remove('active')); b.classList.add('active'); document.querySelectorAll('.view').forEach(x => x.classList.add('hidden')); $(b.dataset.tab).classList.remove('hidden') });
function esc(s) { return s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])) }
